### ISSUE TITLE
error importing as bucket

### ISSUE THREAD

**Issue by jeremyforest** [NicoWeio/aw-watcher-atom#1]
Hi,

I'm on Ubuntu 20.04 and started to play around with aw. 
Trying to import this add-on with Raw Data --> Import and export buckets --> then choosing the json file
I think that is the right way to do it but correct me if I'm wrong. 
I git cloned the aw-watcher-atom into the main activity watch folder. 

Getting this error: 

```
 
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1950, in full_dispatch_request
  File "site-packages/flask/app.py", line 1936, in dispatch_request
  File "site-packages/flask_restx/api.py", line 339, in wrapper
  File "site-packages/flask/views.py", line 89, in view
  File "site-packages/flask_restx/resource.py", line 44, in dispatch_request
  File "aw_server/rest.py", line 291, in post
KeyError: 'buckets'
2021-02-18 14:14:34 [INFO ]: 500 (127.0.0.1): POST /api/0/import HTTP/1.1  (flask:25)

```

**Comment by jeremyforest** [comment]
Ok never mind just realized this should be installed in atom directly. Closing now.

**Comment by NicoWeio** [comment]
Exactly, this is meant to be installed as an Atom package. I didn't really consider that people might come from other places and not know what this repo is for, so I didn't make that clear in the README. 
I just added a section to it that should clarify how to install this package (2a520ae). Let me know if it's better now! :)

**Comment by jeremyforest** [comment]
Looks perfect ! Thanks !!
